# Generated by Django 6.0.5 on 2026-05-25 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_post_likes_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
    ]
